import re
file = 'renderer'+'.js'
with open (file, 'r+' , encoding='utf-8') as f1:
    text5 = f1.read()
    pattern1 = r'(children:"Completely reinstall this software")'
    pattern2 = r'(Close any software that occupies 443 or 42098 port)'
    pattern3 = r'(Add this software into antivirus whitelist)'
    pattern4 = r'(Run in administrator mode)'
    pattern5 = r'(Backend server start failed. You must fix this problem before you can use this software. Try the following and restart this application:)'
    pattern6 = r'(This license is blocked, please contact author.)'
    pattern7 = r'("License is blocked")'
    pattern8 = r'(This device is blocked, please contact author.)'
    pattern9 = r'("Device is blocked")'
    pattern10 = r'(This version is too old. Please update to the latest version. All functions will be disabled.)'
    pattern11 = r'(How to use this?)'
    pattern12 = r'(You can change the color of the ground texture either on the world map or while you are flying. The color changes will take effect when new images are loaded.)'
    pattern13 = r'(If you have enabled the “Rolling cache” feature in the game, you might not notice the difference. Please disable it to see the changes.)'
    pattern14 = r'(Current map:)'
    pattern15 = r'(children:"Red")'
    pattern16 = r'(children:"Green")'
    pattern17 = r'(children:"Blue")'
    pattern18 = r'(children:"Brightness")'
    pattern19 = r'(children:"Contrast")'
    pattern20 = r'(children:"Saturation")'
    pattern21 = r'(For Chinese users)'
    pattern22 = r'(In some places, Google servers are blocked. You should set up a proxy first.)'
    pattern23 = r'(Server 1 has 4 load-balanced servers and the mod will randomly pick one to use.)'
    pattern24 = r'(Server 2 is a backup of Server 1 and only has one server to use.)'
    pattern25 = r'(Apple Map satellite images. Please only use for entertainment purposes.)'
    pattern26 = r'(HighLOD is enabled by default.)'
    pattern27 = r"(Mapbox provides better and newer images in some places. The Pro version doesn't require a token compared to the free version.)"
    pattern28 = r'(Google Maps Server provides the best resolution when flying low and seems very up-to-date.)'  
    pattern29 = r'(provides tuned color and resolution.)'
    pattern30 = r"(MSFS's Bing Map is quite old in the game. Selecting this will replace the Bing Map with the latest Bing Map)"
    pattern31 = r'(ArcGIS Server provides more natural color than Google Server in some areas, but it lacks high-resolution data when flying low.)'
    pattern32 = r'(Some areas have different satellite images in different resolutions, so you will see image changes when flying low.)'
    pattern33 = r'(ArcGIS Server does not need to use a proxy.)'
    pattern34 = r'(Mapbox provides better and newer images in some places, please sign up a free key in)'
    pattern35 = r'(and input it in config.)'
    pattern36 = r'(Mapbox access token provides 200,000 tiles for free, please consider using the Rolling Cache inside the game or enabling the Cache inside this mod.)'
    pattern37 = r'(WARNING: There are several users who have told me that they get huge billing from Mapbox. Please note that this app consumes images very quickly, especially when HighLOD is turned on.)'
    pattern38 = r'(Start MSFS on mod start)'
    pattern39 = r'(When enabled, the image server loads 4 images from the next LOD level.)'
    pattern40 = r'(and input it below.)'
    pattern41 = r'(It is recommended to enable cache to increase loading speed and save bandwidth. )'
    pattern42 = r'(Start Options)'
    pattern43 = r'(Go to tray when close application)'
    pattern44 = r'(Game Store)'
    pattern45 = r'(Go to tray after start)'
    pattern46 = r'(Map options)'
    pattern47 = r'(Although this can provide higher resolution and improve image quality, loading speed may slow because 4x images need to be loaded.)'
    pattern48 = r'(High LOD Enabled)'
    pattern49 = r'(Mapbox provides better and newer images in some places. Please sign up for a free key at)'
    pattern50 = r'(Mapbox access token only provides 200,000 tiles for free and can be used up easily.)'
    pattern51 = r'(Auto start mod)'
    pattern52 = r'(Cache options)'
    pattern53 = r"(The cache is used to speed up satellite image loading when MSFS2020's Rolling Cache is disabled. MSFS2020's Rolling Cache may cause issues when switching maps.)"
    pattern54 = r"(Rolling Cache can be turned on while the mod's cache is on if you stick to one server provider.)"
    pattern55 = r"(The cache file can't be set to the rolling game file; they are different.)"
    pattern56 = r'(Cache Enabled)'
    pattern57 = r'(children:"Path")'
    pattern58 = r'(Choose cache file)'
    pattern59 = r'(Use default location)'
    pattern60 = r'(Clearing cache)'
    pattern61 = r'(Please wait a while)'
    pattern62 = r'(Clean cache failed. If the file is locked you can try to close this application and delete the file.)'
    pattern63 = r'(Cache deleted)'
    pattern64 = r'(Cache file size limit GB (0 means unlimited))'
    pattern65 = r'(when the limitation is reached the application will stop putting new content in.)'
    pattern66 = r'(Proxy Settings)'
    pattern67 = r'(same as)'
    pattern68 = r"(If you need a proxy to access Google, please fill in the proxy address in the format http://ip:port or socks5://ip:port. Leave it blank if you don't need a proxy to access Google.)"
    pattern69 = r'(HTTP Proxy or Socks5 Proxy)'
    pattern70 = r'(Proxy test started)'
    pattern71 = r'(Please wait several seconds)'
    pattern72 = r'(Proxy test passed)'
    pattern73 = r'(Proxy test failed)'
    pattern74 = r'(Test Proxy)'
    pattern75 = r'(Network Setting)'
    pattern76 = r'(Network profile)'
    pattern77 = r'(This is the default network configuration that was used before version 7.1.3. It is generally more stable and reliable.)'
    pattern78 = r'(This is a new network configuration that has been fine-tuned for better performance.)'
    pattern79 = r'(If you encounter any network problems, such as getting stuck on the loading screen, slow game loading speed, or ground texture not loading properly, please try switching the network profile. The change will take effect immediately.)'
    pattern80 = r'(Privacy)'
    pattern81 = r'(To help me get enough data to improve this application, please let it enabled. If you have any concern, you can turn it off.)'
    pattern82 = r'(Allow collecting anonymous logs to remote server)'
    pattern83 = r'(Update channel)'
    pattern84 = r'(The application is stable. Choosing this version will only get you the stable version.)'
    pattern85 = r'(means the application works, but may have some bugs.)'
    pattern86 = r'(means the application is not stable and is in active development.)'
    pattern87 = r'(Latest stable version)'
    pattern88 = r'(children:"Reset to default")'
    pattern89 = r'(children:"License")'
    pattern90 = r'(Please select a valid license file.)'
    pattern91 = r'(Open license file failed)'
    pattern92 = r'(Buy a license)'
    pattern93 = r'(children:"Name")'
    pattern94 = r'(to generate a new one.)'
    pattern95 = r'(If you changed your hardware or reinstalled system, please follow)'
    pattern96 = r'(Copy device id)'
    pattern97 = r'("Device Id")'
    pattern98 = r'(Clear license file failed)'
    pattern99 = r'(Error response:)'
    pattern100 = r'("Open license")'
    pattern101 = r'("Clear license")'
    pattern102 = r'(No license)'
    pattern103 = r'("Email")'
    pattern104 = r'(Validate to)'
    pattern105 = r'("Map Enhancement ")'
    pattern106 = r'(Photo by)'
    pattern107 = r'(children:"Reload")'
    pattern108 = r'(For Chinese users)'
    pattern109 = r'(to purchase a license)'
    pattern110 = r'(This map server requires a license. Please activate your license first.)'
    pattern111 = r'(Need license)'
    pattern112 = r'(Software is blocked)'
    pattern113 = r'(Please download latest version or contact author for help)'
    pattern114 = r'(to retry)'
    pattern115 = r'(Please restart the app or press)'
    pattern116 = r'(Also, please check if any application is occupying ports 443 or 42098. The app must be running in administrator mode.)'
    pattern117 = r'(Create a new hosts file)'
    pattern118 = r'(Disable any global proxies)'
    pattern119 = r'(Image server test failed)'
    pattern120 = r'(If you are using a proxy to connect to the remote server, please ensure that the proxy is working. )'
    pattern121 = r'(Please also visit)'
    pattern122 = r'(Turn off your antivirus and restart your computer.)'
    pattern123 = r'("Run as administrator.")'
    pattern124 = r'(Unable to patch hosts file. Please try:)'
    pattern125 = r'(Apply hosts change failed)'
    pattern126 = r'(Check if any tools inside your antivirus are protecting your system)'
    pattern127 = r'(Try adding this mod to the whitelist)'
    pattern128 = r'(Try turning off your antivirus and restarting your computer)'
    pattern129 = r"(Can't install certificate, please try:)"
    pattern130 = r'(Install certificate error)'
    pattern131 = r'(Please switch to a different server. Otherwise, MSFS2020 will fail to load.)'
    pattern132 = r'(Unable to access remote image server)'
    pattern133 = r'(Select a map)'
    pattern134 = r'(Please wait a moment and try again.)'
    pattern135 = r'(Backend server is starting)'
    pattern136 = r'(Backend server start failed)'
    pattern137 = r'(MS server override is not working MSFS2020)'
    pattern138 = r'("Please try:")'
    pattern139 = r'(Disable any game accelerator)'
    pattern140 = r'(in your browser. You may be blocked by Google due to a large number of requests.)'
    pattern141 = r'(If you are using Google Maps, please ensure that you can open)'
    pattern142 = r'(Check if any tools inside your antivirus are protecting your system.)'
    pattern143 = r'(For more information, please visit the)'
    pattern144 = r'(Add this mod into white list.)'
    pattern145 = r'("for more information.")'
    pattern146 = r'(children:"Reset")'
    pattern147 = r'(Select a mixed map)'
    pattern148 = r'(children:"Start")'
    pattern149 = r'(name:"Start")'
    pattern150 = r'(children:"Note")'
    pattern151 = r'(Please first visit)'
    pattern152 = r'(for common issues. Most issues are explained and can be solved there.)'
    pattern153 = r"(If you still can't fix it or have other issues, please provide this information and also log file for me and raise an issue:)"
    pattern154 = r'(Create a new issue)'
    pattern155 = r'(name:"Color")'
    pattern156 = r'(name:"License")'
    pattern157 = r'(name:"Help")'
    pattern158 = r'(Loaded Images)'
    pattern159 = r'(Current Image)'
    pattern160 = r'(Image From Cache)'
    pattern161 = r'(Image server error)'
    pattern162 = r'(Restore hosts file failed)'
    pattern163 = r'("Normal LOD")'
    pattern164 = r'("High LOD")'
    pattern165 = r'(Total data)'
    pattern166 = r'(Cache Size)'
    pattern167 = r'(name:"Settings")'
    pattern168 = r'(Detail:)'
    pattern169 = r'(国外地图需要在Select mixed map中选择一个国外源，当从国内飞国外时会自动切换。)'
    pattern170 = r'(2021年中国超清地图)'
    pattern171 = r'(children:"Stop")'
    pattern172 = r'("The free version has the original color from Google Maps and the data may be older than the Pro version.")'
    pattern173 = r'(For example, when MSFS2020 requests images from level 19, the image server loads 4 images from level 19 and merges them.)'
    pattern174 = r'(The image sent to MSFS2020 is a 512*512)'
    pattern175 = r'(image compared to the original 256*256 image.)'
    pattern176 = r'(Some people have already received bills of over $200 from Mapbox.)'
    pattern177 = r'(Please monitor your usage carefully.)'
    pattern178 = r'(children:"Alpha version")'
    pattern179 = r'(children:"Beta version")'
    pattern180 = r'(children:"MS Store")'
    pattern181 = r'(When enable this option, the image server will load HD images when you are flying. This will provide better loading speed.)'
    pattern182 = r'(Load High LOD images only when flying)'
    pattern183 = r"(If you still can't fix it or have other issues, please)"
    pattern184 = r"(let me know)"
    text5 = re.sub(pattern1,'children:"完全重新安装此软件"',text5)
    text5 = re.sub(pattern2,'关闭任何占用443或42098端口的软件',text5)
    text5 = re.sub(pattern3,'将本软件加入杀毒软件白名单',text5)
    text5 = re.sub(pattern4,'以管理员模式运行',text5)
    text5 = re.sub(pattern5,'后端服务器启动失败, 您必须解决此问题才能使用此软件, 尝试以下操作并重新启动此应用程序：',text5)
    text5 = re.sub(pattern6,'此许可证已被禁止使用，请联系作者。',text5)
    text5 = re.sub(pattern7,'"此许可证已被禁止使用"',text5)
    text5 = re.sub(pattern8,'此设备已被禁止使用，请联系作者。',text5)
    text5 = re.sub(pattern9,'"此设备已被禁止使用"',text5)
    text5 = re.sub(pattern10,'该版本已经停止支持，在更新到最新版本之前，停止使用所有功能',text5)
    text5 = re.sub(pattern11,'如何使用此功能',text5)
    text5 = re.sub(pattern12,'您可以在世界地图上或飞行时更改地面纹理的颜色，颜色更改将在加载新图像时生效。',text5)
    text5 = re.sub(pattern13,'如果您在游戏中启用了“滚动缓存”功能，您可能不会注意到其中的区别，请禁用“滚动缓存”功能以查看更改。',text5)
    text5 = re.sub(pattern14,'当前地图：',text5)
    text5 = re.sub(pattern15,'children:"红色"',text5)
    text5 = re.sub(pattern16,'children:"绿色"',text5)
    text5 = re.sub(pattern17,'children:"蓝色"',text5)
    text5 = re.sub(pattern18,'children:"明亮程度"',text5)
    text5 = re.sub(pattern19,'children:"对比度"',text5)
    text5 = re.sub(pattern20,'children:"饱和度"',text5)
    text5 = re.sub(pattern21,'对于中国用户',text5)
    text5 = re.sub(pattern22,'在某些地方，谷歌服务器不能访问，您应该先设置代理。',text5)
    text5 = re.sub(pattern23,'Google Maps Server 1 有4个负载平衡服务器，插件会随机选择一个使用。',text5)
    text5 = re.sub(pattern24,'Google Maps Server 2 是 Google Maps Server 1 的备份，只有一台服务器可以使用。',text5)
    text5 = re.sub(pattern25,'Apple Map 卫星图像，请仅用于娱乐目的。',text5)
    text5 = re.sub(pattern26,'HighLOD 默认开启。',text5)
    text5 = re.sub(pattern27,'Mapbox 在某些地方提供了更好和更新的图像, 与免费版相比, Pro 不需要令牌。',text5)
    text5 = re.sub(pattern28,'谷歌地图服务器在低空飞行时提供最佳分辨率，而且看起来是最新的。',text5)
    text5 = re.sub(pattern29,'提供经过调整的颜色和分辨率。',text5)
    text5 = re.sub(pattern30,'MSFS 的 Bing 地图在游戏中相当古老。 选择此项会将 Bing 地图替换为最新的 Bing 地图',text5)
    text5 = re.sub(pattern31,'ArcGIS Server 在某些区域提供比 Google Server 更自然的颜色，但在低空飞行时缺乏高分辨率数据。',text5)
    text5 = re.sub(pattern32,'有些地区有不同分辨率的不同卫星图像，所以当你低空飞行时你会看到图像变化。',text5)
    text5 = re.sub(pattern33,'ArcGIS Server 不需要代理。',text5)
    text5 = re.sub(pattern34,'Mapbox 在某些地方提供了更好和更新的图像，请到官网注册免费密钥',text5)
    text5 = re.sub(pattern35,'然后填入设置的Mapbox选项',text5)
    text5 = re.sub(pattern36,'Mapbox 访问令牌免费提供 200,000 个图块，请考虑在游戏中使用滚动缓存或在本模组中启用缓存。',text5)
    text5 = re.sub(pattern37,'注意！有部分用户告诉我他们从 Mapbox 获得了巨额账单。请注意，此应用程序消耗图像的速度非常快，尤其是在打开 HighLOD 时。',text5)
    text5 = re.sub(pattern38,'在插件启动时启动 MSFS',text5)
    text5 = re.sub(pattern39,'启用后，图像服务器从下一个 LOD 级别加载 4 个图像。',text5)
    text5 = re.sub(pattern40,'并填入。',text5)
    text5 = re.sub(pattern41,'建议启用缓存以提高加载速度并节省流量。',text5)
    text5 = re.sub(pattern42,'启动选项',text5)
    text5 = re.sub(pattern43,'关闭应用程序时，最小化到托盘',text5)
    text5 = re.sub(pattern44,'游戏商店版本',text5)
    text5 = re.sub(pattern45,'启动后自动转到系统托盘',text5)
    text5 = re.sub(pattern46,'地图设置',text5)
    text5 = re.sub(pattern47,'虽然这可以提供更高的分辨率并提高图像质量，但加载速度可能会变慢，因为需要加载 4x 图像。',text5)
    text5 = re.sub(pattern48,'High LOD 开启',text5)
    text5 = re.sub(pattern49,'Mapbox 在某些地方提供了更好和更新的图像。 请点击链接注册免费密钥',text5)
    text5 = re.sub(pattern50,'Mapbox access token 只免费提供 200,000个图片，很容易用完。',text5)
    text5 = re.sub(pattern51,'自动开启插件',text5)
    text5 = re.sub(pattern52,'缓存设置',text5)
    text5 = re.sub(pattern53,'插件缓存用于在禁用MSFS2020里的滚动缓存时加速卫星图像加载， MSFS2020的滚动缓存可能会导致切换地图时出现问题。',text5)
    text5 = re.sub(pattern54,'如果您一直在使用一个地图服务器，则可以在插件的缓存打开时打开MSFS2020的滚动缓存。',text5)
    text5 = re.sub(pattern55,'缓存文件不能设置为滚动游戏文件，这两个文件是不同的。',text5)
    text5 = re.sub(pattern56,'缓存开启',text5)
    text5 = re.sub(pattern57,'children:"路径"',text5)
    text5 = re.sub(pattern58,'选择缓存文件',text5)
    text5 = re.sub(pattern59,'使用默认路径',text5)
    text5 = re.sub(pattern60,'清除缓存',text5)
    text5 = re.sub(pattern61,'请等待',text5)
    text5 = re.sub(pattern62,'清理缓存失败。如果文件被锁定，您可以尝试关闭此应用程序并删除该文件。',text5)
    text5 = re.sub(pattern63,'缓存已删除',text5)
    text5 = re.sub(pattern64,'缓存文件大小限制 GB（0 表示无限制）',text5)
    text5 = re.sub(pattern65,'当达到限制时，应用程序将停止添加新内容。',text5)
    text5 = re.sub(pattern66,'代理设置',text5)
    text5 = re.sub(pattern67,'例如',text5)
    text5 = re.sub(pattern68,'如果您需要代理访问Google，请填写代理地址，格式为http://ip:port 或socks5://ip:port。如果您不需要代理来访问 Google，请将其留空。',text5)
    text5 = re.sub(pattern69,'HTTP 代理或 Socks5 代理',text5)
    text5 = re.sub(pattern70,'代理测试开始',text5)
    text5 = re.sub(pattern71,'请等待几秒钟',text5)
    text5 = re.sub(pattern72,'代理测试通过',text5)
    text5 = re.sub(pattern73,'代理测试失败',text5)
    text5 = re.sub(pattern74,'测试代理状态',text5)
    text5 = re.sub(pattern75,'网络设置',text5)
    text5 = re.sub(pattern76,'网络概况',text5)
    text5 = re.sub(pattern77,'这是7.1.3版本之前使用的默认网络配置。该配置更加稳定和可靠。',text5)
    text5 = re.sub(pattern78,'这是一种新的网络配置，经过微调以获得更好的性能。',text5)
    text5 = re.sub(pattern79,'如果您遇到任何网络问题，例如加载画面卡住、游戏加载速度慢或地面纹理无法正常加载，请尝试切换网络配置文件。更改将立即生效。',text5)
    text5 = re.sub(pattern80,'隐私条款',text5)
    text5 = re.sub(pattern81,'为了帮助我获得足够的数据来改进此应用程序，请启用它。如果您有任何疑问或者担心，可以将其关闭。',text5)
    text5 = re.sub(pattern82,'允许收集匿名日志到远程服务器',text5)
    text5 = re.sub(pattern83,'版本选择',text5)
    text5 = re.sub(pattern84,'应用处于稳定版，选择此版本只会为您提供稳定版本。',text5)
    text5 = re.sub(pattern85,'表示应用程序可以运行，但可能存在一些错误。',text5)
    text5 = re.sub(pattern86,'表示应用程序不稳定并且正在积极开发中。',text5)
    text5 = re.sub(pattern87,'Latest stable 版本',text5)
    text5 = re.sub(pattern88,'children:"重置为默认设置"',text5)
    text5 = re.sub(pattern89,'children:"Pro 授权"',text5)
    text5 = re.sub(pattern90,'请选择有效的授权文件。',text5)
    text5 = re.sub(pattern91,'打开授权文件失败',text5)
    text5 = re.sub(pattern92,'购买授权',text5)
    text5 = re.sub(pattern93,'children:"购买用户名"',text5)
    text5 = re.sub(pattern94,'去重新生成一个授权文件',text5)
    text5 = re.sub(pattern95,'如果您更改了硬件或重新安装了系统，请按照',text5)
    text5 = re.sub(pattern96,'复制设备ID',text5)
    text5 = re.sub(pattern97,'"设备ID"',text5)
    text5 = re.sub(pattern98,'清除授权文件失败',text5)
    text5 = re.sub(pattern99,'错误：',text5)
    text5 = re.sub(pattern100,'"选择授权文件"',text5)
    text5 = re.sub(pattern101,'"清除授权"',text5)
    text5 = re.sub(pattern102,'无授权',text5)
    text5 = re.sub(pattern103,'"邮箱"',text5)
    text5 = re.sub(pattern104,'授权有效期',text5)
    text5 = re.sub(pattern105,'"MSFS2020 地图增强器 "',text5)
    text5 = re.sub(pattern106,'照片拍摄于：',text5)
    text5 = re.sub(pattern107,'children:"重新加载"',text5)
    text5 = re.sub(pattern108,'对于中国用户',text5)
    text5 = re.sub(pattern109,'购买许可证',text5)
    text5 = re.sub(pattern110,'该地图需要Pro 授权，请点击授权进行购买',text5)
    text5 = re.sub(pattern111,'需要授权',text5)
    text5 = re.sub(pattern112,'软件被锁定',text5)
    text5 = re.sub(pattern113,'请下载最新版本或联系作者寻求帮助',text5)
    text5 = re.sub(pattern114,'重试',text5)
    text5 = re.sub(pattern115,'请重新启动应用程序或按',text5)
    text5 = re.sub(pattern116,'另外，请检查是否有任何应用程序占用了443或42098端口，该应用程序必须在管理员模式下运行。',text5)
    text5 = re.sub(pattern117,'选择新的Host文件',text5)
    text5 = re.sub(pattern118,'禁用所有全局代理',text5)
    text5 = re.sub(pattern119,'地图服务器测试失败',text5)
    text5 = re.sub(pattern120,'如果您使用代理连接远程服务器，请确保代理正常工作。',text5)
    text5 = re.sub(pattern121,'还请访问',text5)
    text5 = re.sub(pattern122,'关闭杀毒软件并重新启动计算机。',text5)
    text5 = re.sub(pattern123,'"以管理员身份运行。"',text5)
    text5 = re.sub(pattern124,'无法修补Host文， 请尝试：',text5)
    text5 = re.sub(pattern125,'应用主机更改失败',text5)
    text5 = re.sub(pattern126,'检查杀毒软件中的任何工具是否正在保护您的系统',text5)
    text5 = re.sub(pattern127,'尝试将此插件添加到白名单',text5)
    text5 = re.sub(pattern128,'尝试关闭杀毒软件并重新启动计算机',text5)
    text5 = re.sub(pattern129,'无法安装证书，请尝试：',text5)
    text5 = re.sub(pattern130,'安装证书错误',text5)
    text5 = re.sub(pattern131,'请使用不同的服务器。否则，MSFS2020将无法加载。',text5)
    text5 = re.sub(pattern132,'无法访问远程地图服务器',text5)
    text5 = re.sub(pattern133,'选择一个地图',text5)
    text5 = re.sub(pattern134,'请稍等片刻，然后重试。',text5)
    text5 = re.sub(pattern135,'后端服务器正在启动',text5)
    text5 = re.sub(pattern136,'后端服务器启动失败',text5)
    text5 = re.sub(pattern137,'MSFS2020 地图覆盖不起作用',text5)
    text5 = re.sub(pattern138,'"请尝试："',text5)
    text5 = re.sub(pattern139,'禁用任何游戏加速器',text5)
    text5 = re.sub(pattern140,'在您的浏览器中, 由于大量请求，您可能会被 Google 屏蔽。',text5)
    text5 = re.sub(pattern141,'如果您使用的是Google地图，请确保您可以打开地图',text5)
    text5 = re.sub(pattern142,'检查杀毒软件中是否有任何工具正在保护您的系统。',text5)
    text5 = re.sub(pattern143,'欲了解更多信息，请访问',text5)
    text5 = re.sub(pattern144,'将此插件添加到白名单中。',text5)
    text5 = re.sub(pattern145,'"了解更多信息。"',text5)
    text5 = re.sub(pattern146,'children:"重置"',text5)
    text5 = re.sub(pattern147,'选择混合地图',text5)
    text5 = re.sub(pattern148,'children:"应用服务器"',text5)
    text5 = re.sub(pattern149,'name:"首页"',text5)
    text5 = re.sub(pattern150,'children:"关于"',text5)
    text5 = re.sub(pattern151,'请先访问',text5)
    text5 = re.sub(pattern152,'对于常见问题。 大多数问题都可以在那里得到解释和解决。',text5)
    text5 = re.sub(pattern153,'如果您仍然无法修复它或遇到其他问题，请为开发者提供此信息和日志文件并提出问题：',text5)
    text5 = re.sub(pattern154,'新建一个问题',text5)
    text5 = re.sub(pattern155,'name:"颜色"',text5)
    text5 = re.sub(pattern156,'name:"授权"',text5)
    text5 = re.sub(pattern157,'name:"帮助"',text5)
    text5 = re.sub(pattern158,'加载的地图图片',text5)
    text5 = re.sub(pattern159,'当前图像',text5)
    text5 = re.sub(pattern160,'来自缓存的图像',text5)
    text5 = re.sub(pattern161,'地图服务器错误',text5)
    text5 = re.sub(pattern162,'恢复Host文件失败',text5)
    text5 = re.sub(pattern163,'"正常 LOD"',text5)
    text5 = re.sub(pattern164,'"高 LOD"',text5)
    text5 = re.sub(pattern165,'总数据大小',text5)
    text5 = re.sub(pattern166,'缓存大小',text5)
    text5 = re.sub(pattern167,'name:"设置"',text5)
    text5 = re.sub(pattern168,'详细：',text5)
    text5 = re.sub(pattern169,'国外地图需要在选择混合地图中选择一个国外源，当从国内飞国外时会自动切换。',text5)
    text5 = re.sub(pattern170,'中国定制超清地图2021年最新地图',text5)
    text5 = re.sub(pattern171,'children:"停止应用"',text5)
    text5 = re.sub(pattern172,'"免费版本具有 Google 地图的原始颜色，并且数据可能比 Pro 旧。"',text5)
    text5 = re.sub(pattern173,'例如，当MSFS2020从19级请求图像时，图像服务器从19级加载4张图像并合并它们。',text5)
    text5 = re.sub(pattern174,'与原始 256*256 图像相比，',text5)
    text5 = re.sub(pattern175,'发送到 MSFS2020 的图像是 512*512 图像。（意思就是图更加高清）',text5)
    text5 = re.sub(pattern176,'有些人已经从 Mapbox 收到了超过200美元的账单，',text5)
    text5 = re.sub(pattern177,'请仔细监控您的使用情况。',text5)
    text5 = re.sub(pattern178,'children:"Alpha 版本"',text5)
    text5 = re.sub(pattern179,'children:"Beta 版本"',text5)
    text5 = re.sub(pattern180,'children:"微软商店（Xbox）"',text5)
    text5 = re.sub(pattern181,'启用此选项后，替换插件将在您飞行时加载高清图像。 这将提供更好的加载速度。',text5)
    text5 = re.sub(pattern182,'仅在飞行时加载高 LOD 图像',text5)
    text5 = re.sub(pattern183,'如果您仍然无法修复它或遇到其他问题,请',text5)
    text5 = re.sub(pattern184,'让我知道',text5)
    with open (file,'w',encoding='utf-8') as f2:
        f2.write(text5)